immediate-update = false

# This table is no longer used, but it is an example of key - integer values.
[cities]
Paris = 2
Tokyo = 9
Montreal = -4

# Map labels to timezone city/continent strings.
# You can list these with this sort of thing:
# timedatectl list-timezones | grep Bangkok
[autocities]
Paris = "Europe/Paris"
Tokyo = "Asia/Tokyo"
Montreal = "America/Montreal"

