
1
# 222
this = "that"
again = "something"

[tablea1]  
nerf="narf"
nerf baby = "tudi #chops"
sick=
=sack
sick=   "sack" # OK?
ml='''Hello

there world.'''
so="what"
and='another'
someint = 8394

[]
array=[1,2,3,  4, 5 ]
anint=12345
anotherint = -234
finalint = +999
abool = true
anotherbool = false
abool = false
a=897

string-with-escapes = "Hello\nwill this work?\nA tab here\tor something?"
literal-string-with-escapes = 'Hello\nwill this work?\nA tab here\tor something?'

afloat=3.1415926
